In [2]:
import pandas as pd
import time
from IPython.display import Image
from IPython.core.display import HTML

## Import and Display Stock Data as DataFrame

In [3]:
data = pd.read_csv('stocks.csv')

In [4]:
# preview types of data 
data.head()

         date   open   high    low  close    volume Name
0  2013-02-08  15.07  15.12  14.63  14.75   8407500  AAL
1  2013-02-11  14.89  15.01  14.26  14.46   8882000  AAL
2  2013-02-12  14.45  14.51  14.10  14.27   8126000  AAL
3  2013-02-13  14.30  14.94  14.25  14.66  10259500  AAL
4  2013-02-14  14.94  14.96  13.16  13.99  31879900  AAL

In [6]:
# get a sense of dataset size
data.describe()

,open,high,low,close,volume
count,619029.000000,619032.000000,619032.000000,619040.000000,6.190400e+05
mean,83.023334,83.778311,82.256096,83.043763,4.321823e+06
std,97.378769,98.207519,96.507421,97.389748,8.693610e+06
min,1.620000,1.690000,1.500000,1.590000,0.000000e+00
25%,40.220000,40.620000,39.830000,40.245000,1.070320e+06
50%,62.590000,63.150000,62.020000,62.620000,2.082094e+06
75%,94.370000,95.180000,93.540000,94.410000,4.284509e+06
max,2044.000000,2067.990000,2035.110000,2049.000000,6.182376e+08

## Take data from dataframe and put into nested dictionary structure

In [8]:
data_dict = {}
print("Dictionary building ...\n")
for i in range(0,len(data)):
    values = {}
    dates = {}
    names = {}
    date = data.iat[i,0]
    _open = data.iat[i,1]
    _close = data.iat[i,4]
    _high = data.iat[i,2]
    _low = data.iat[i,3]
    name = data.iat[i,6]
    volume = data.iat[i,5]
    values['open'] = _open
    values['close'] = _close
    values['high'] = _high
    values['low'] = _low
    if name not in data_dict:
        date_dict = {}
        values_dict = {}
        date_dict[date] = {'open':_open,'close':_close,'low':_low,'high':_high,'volume':volume}
        data_dict[name] = date_dict
    else:
        date_dict[date] = {'open':_open,'close':_close,'low':_low,'high':_high,'volume':volume}
print("Dictionary created.")

Dictionary building ...

Dictionary created.

## Interactive Demo Segment - Pick a Winner

In [9]:
test_df = data.set_index('date')

In [10]:
test_df.loc['2013-04-10'][test_df.loc['2013-04-10']['Name'] == 'GOOGL']['volume'].tolist()[0]

3953171

In [17]:
start_time = time.time()
test_df.loc['2013-04-10'][test_df.loc['2013-04-10']['Name'] == 'GOOGL']['volume'].tolist()[0]
print("dataframe search took: \n --- %s seconds ---" % (time.time() - start_time))
df_lookup = (time.time() - start_time)

dataframe search took:
 --- 0.025815725326538086 seconds ---

In [18]:
data_dict['GOOGL']['2013-04-10']['volume']

3953171

In [19]:
start_time = time.time()
data_dict['GOOGL']['2013-04-10']['volume']
print("dictionary search took: \n--- %s seconds ---" % (time.time() - start_time))
dict_lookup = (time.time() - start_time)

dictionary search took:
--- 6.29425048828125e-05 seconds ---

# And the winner is ...

In [21]:
try:
    print('Dictionary search is: ',df_lookup/dict_lookup, ' times faster')
except:
    print('Cannot divide by zero')

Dictionary search is:  98.95557570262919  times faster

### Get unique company names

In [22]:
#Get unique company names
company_list = data['Name'].unique().tolist()
company_list

['AAL',
 'AAPL',
 'AAP',
 'ABBV',
 'ABC',
 'ABT',
 'ACN',
 'ADBE',
 'ADI',
 'ADM',
 'ADP',
 'ADSK',
 'ADS',
 'AEE',
 'AEP',
 'AES',
 'AET',
 'AFL',
 'AGN',
 'AIG',
 'AIV',
 'AIZ',
 'AJG',
 'AKAM',
 'ALB',
 'ALGN',
 'ALK',
 'ALLE',
 'ALL',
 'ALXN',
 'AMAT',
 'AMD',
 'AME',
 'AMGN',
 'AMG',
 'AMP',
 'AMT',
 'AMZN',
 'ANDV',
 'ANSS',
 'ANTM',
 'AON',
 'AOS',
 'APA',
 'APC',
 'APD',
 'APH',
 'APTV',
 'ARE',
 'ARNC',
 'ATVI',
 'AVB',
 'AVGO',
 'AVY',
 'AWK',
 'AXP',
 'AYI',
 'AZO',
 'A',
 'BAC',
 'BAX',
 'BA',
 'BBT',
 'BBY',
 'BDX',
 'BEN',
 'BF.B',
 'BHF',
 'BHGE',
 'BIIB',
 'BK',
 'BLK',
 'BLL',
 'BMY',
 'BRK.B',
 'BSX',
 'BWA',
 'BXP',
 'CAG',
 'CAH',
 'CAT',
 'CA',
 'CBG',
 'CBOE',
 'CBS',
 'CB',
 'CCI',
 'CCL',
 'CDNS',
 'CELG',
 'CERN',
 'CFG',
 'CF',
 'CHD',
 'CHK',
 'CHRW',
 'CHTR',
 'CINF',
 'CI',
 'CLX',
 'CL',
 'CMA',
 'CMCSA',
 'CME',
 'CMG',
 'CMI',
 'CMS',
 'CNC',
 'CNP',
 'COF',
 'COG',
 'COL',
 'COO',
 'COP',
 'COST',
 'COTY',
 'CPB',
 'CRM',
 'CSCO',
 'CSRA',
 'CSX',
 'CTAS',
 'CTL',
 'CTSH',
 'CTXS',
 'CVS',
 'CVX',
 'CXO',
 'C',
 'DAL',
 'DE',
 'DFS',
 'DGX',
 'DG',
 'DHI',
 'DHR',
 'DISCA',
 'DISCK',
 'DISH',
 'DIS',
 'DLR',
 'DLTR',
 'DOV',
 'DPS',
 'DRE',
 'DRI',
 'DTE',
 'DUK',
 'DVA',
 'DVN',
 'DWDP',
 'DXC',
 'D',
 'EA',
 'EBAY',
 'ECL',
 'ED',
 'EFX',
 'EIX',
 'EL',
 'EMN',
 'EMR',
 'EOG',
 'EQIX',
 'EQR',
 'EQT',
 'ESRX',
 'ESS',
 'ES',
 'ETFC',
 'ETN',
 'ETR',
 'EVHC',
 'EW',
 'EXC',
 'EXPD',
 'EXPE',
 'EXR',
 'FAST',
 'FBHS',
 'FB',
 'FCX',
 'FDX',
 'FE',
 'FFIV',
 'FISV',
 'FIS',
 'FITB',
 'FLIR',
 'FLR',
 'FLS',
 'FL',
 'FMC',
 'FOXA',
 'FOX',
 'FRT',
 'FTI',
 'FTV',
 'F',
 'GD',
 'GE',
 'GGP',
 'GILD',
 'GIS',
 'GLW',
 'GM',
 'GOOGL',
 'GOOG',
 'GPC',
 'GPN',
 'GPS',
 'GRMN',
 'GS',
 'GT',
 'GWW',
 'HAL',
 'HAS',
 'HBAN',
 'HBI',
 'HCA',
 'HCN',
 'HCP',
 'HD',
 'HES',
 'HIG',
 'HII',
 'HLT',
 'HOG',
 'HOLX',
 'HON',
 'HPE',
 'HPQ',
 'HP',
 'HRB',
 'HRL',
 'HRS',
 'HSIC',
 'HST',
 'HSY',
 'HUM',
 'IBM',
 'ICE',
 'IDXX',
 'IFF',
 'ILMN',
 'INCY',
 'INFO',
 'INTC',
 'INTU',
 'IPG',
 'IP',
 'IQV',
 'IRM',
 'IR',
 'ISRG',
 'ITW',
 'IT',
 'IVZ',
 'JBHT',
 'JCI',
 'JEC',
 'JNJ',
 'JNPR',
 'JPM',
 'JWN',
 'KEY',
 'KHC',
 'KIM',
 'KLAC',
 'KMB',
 'KMI',
 'KMX',
 'KORS',
 'KO',
 'KR',
 'KSS',
 'KSU',
 'K',
 'LB',
 'LEG',
 'LEN',
 'LH',
 'LKQ',
 'LLL',
 'LLY',
 'LMT',
 'LNC',
 'LNT',
 'LOW',
 'LRCX',
 'LUK',
 'LUV',
 'LYB',
 'L',
 'MAA',
 'MAC',
 'MAR',
 'MAS',
 'MAT',
 'MA',
 'MCD',
 'MCHP',
 'MCK',
 'MCO',
 'MDLZ',
 'MDT',
 'MET',
 'MGM',
 'MHK',
 'MKC',
 'MLM',
 'MMC',
 'MMM',
 'MNST',
 'MON',
 'MOS',
 'MO',
 'MPC',
 'MRK',
 'MRO',
 'MSFT',
 'MSI',
 'MS',
 'MTB',
 'MTD',
 'MU',
 'MYL',
 'M',
 'NAVI',
 'NBL',
 'NCLH',
 'NDAQ',
 'NEE',
 'NEM',
 'NFLX',
 'NFX',
 'NI',
 'NKE',
 'NLSN',
 'NOC',
 'NOV',
 'NRG',
 'NSC',
 'NTAP',
 'NTRS',
 'NUE',
 'NVDA',
 'NWL',
 'NWSA',
 'NWS',
 'OKE',
 'OMC',
 'ORCL',
 'ORLY',
 'OXY',
 'O',
 'PAYX',
 'PBCT',
 'PCAR',
 'PCG',
 'PCLN',
 'PDCO',
 'PEG',
 'PEP',
 'PFE',
 'PFG',
 'PGR',
 'PG',
 'PHM',
 'PH',
 'PKG',
 'PKI',
 'PLD',
 'PM',
 'PNC',
 'PNR',
 'PNW',
 'PPG',
 'PPL',
 'PRGO',
 'PRU',
 'PSA',
 'PSX',
 'PVH',
 'PWR',
 'PXD',
 'PX',
 'PYPL',
 'QCOM',
 'QRVO',
 'RCL',
 'REGN',
 'REG',
 'RE',
 'RF',
 'RHI',
 'RHT',
 'RJF',
 'RL',
 'RMD',
 'ROK',
 'ROP',
 'ROST',
 'RRC',
 'RSG',
 'RTN',
 'SBAC',
 'SBUX',
 'SCG',
 'SCHW',
 'SEE',
 'SHW',
 'SIG',
 'SJM',
 'SLB',
 'SLG',
 'SNA',
 'SNI',
 'SNPS',
 'SO',
 'SPGI',
 'SPG',
 'SRCL',
 'SRE',
 'STI',
 'STT',
 'STX',
 'STZ',
 'SWKS',
 'SWK',
 'SYF',
 'SYK',
 'SYMC',
 'SYY',
 'TAP',
 'TDG',
 'TEL',
 'TGT',
 'TIF',
 'TJX',
 'TMK',
 'TMO',
 'TPR',
 'TRIP',
 'TROW',
 'TRV',
 'TSCO',
 'TSN',
 'TSS',
 'TWX',
 'TXN',
 'TXT',
 'T',
 'UAA',
 'UAL',
 'UA',
 'UDR',
 'UHS',
 'ULTA',
 'UNH',
 'UNM',
 'UNP',
 'UPS',
 'URI',
 'USB',
 'UTX',
 'VAR',
 'VFC',
 'VIAB',
 'VLO',
 'VMC',
 'VNO',
 'VRSK',
 'VRSN',
 'VRTX',
 'VTR',
 'VZ',
 'V',
 'WAT',
 'WBA',
 'WDC',
 'WEC',
 'WFC',
 'WHR',
 'WLTW',
 'WMB',
 'WMT',
 'WM',
 'WRK',
 'WU',
 'WYNN',
 'WYN',
 'WY',
 'XEC',
 'XEL',
 'XLNX',
 'XL',
 'XOM',
 'XRAY',
 'XRX',
 'XYL',
 'YUM',
 'ZBH',
 'ZION',
 'ZTS']

### Time to get opening value of amazon stock on 2018-01-02 with dataframe search

In [24]:
start_time = time.time()
data[(data['Name'] == 'AMZN') & (data['date'] == '2018-01-02')].reset_index(drop=True).iat[0,1]
print("Dataframe search took: \n --- %s seconds ---" % (time.time() - start_time))
df_lookup = (time.time() - start_time)

Dataframe search took:
 --- 0.08478522300720215 seconds ---

### Time to get opening value of Amazon stock on 2018-01-02 with dictionary search

In [25]:
start_time = time.time()
data_dict['AMZN']['2018-01-02']['open']
print("Dictionary search took: \n --- %s seconds ---" % (time.time() - start_time))
dict_lookup = (time.time() - start_time)

Dictionary search took:
 --- 0.00014472007751464844 seconds ---

### Get ratio of dataframe search to dictionary lookup

In [26]:
try:
    print('The dictionary lookup is',df_lookup/dict_lookup,'times faster')
except:
    print('Cannot divide by zero')

The dictionary lookup is 260.54718361375274 times faster

### Get opening values for all companies on 2018-01-02 with dictionaries, print and time it

In [27]:
#Get opening values for all companies on given date
def get_opening_values_with_dicts():
    for company in data['Name'].unique():
        print(company, data_dict[company]['2018-01-02']['open'])

In [33]:
#time to get all opening values with nested dictionaries
print("Gathering opening prices using nested dictionaries \n")
start_time = time.time()
get_opening_values_with_dicts()
dict_time = time.time() - start_time
print("\n\nTotal time to return each company's opening price using dictionaries: \n--- %s seconds ---" % (time.time() - start_time))

Gathering opening prices using nested dictionaries

AAL 52.33
AAPL 170.16
AAP 100.9
ABBV 97.14
ABC 92.15
ABT 58.2
ACN 153.5
ADBE 175.85
ADI 89.24
ADM 40.2
ADP 116.03
ADSK 105.34
ADS 254.29
AEE 58.98
AEP 73.18
AES 10.87
AET 180.94
AFL 88.36
AGN 164.05
AIG 60.0
AIV 43.79
AIZ 101.44
AJG 63.55
AKAM 65.13
ALB 128.93
ALGN 222.61
ALK 74.04
ALLE 80.07
ALL 104.07
ALXN 121.63
AMAT 51.68
AMD 10.42
AME 72.89
AMGN 175.35
AMG 206.52
AMP 170.64
AMT 143.16
AMZN 1172.0
ANDV 114.92
ANSS 148.15
ANTM 225.0
AON 134.25
AOS 61.45
APA 42.65
APC 54.13
APD 164.88
APH 88.47
APTV 84.89
ARE 131.0
ARNC 27.31
ATVI 63.54
AVB 178.59
AVGO 259.77
AVY 115.15
AWK 91.0
AXP 99.73
AYI 176.67
AZO 716.54
A 67.42
BAC 29.75
BAX 66.09
BA 295.75
BBT 50.0
BBY 68.26
BDX 215.09
BEN 43.77
BF.B 68.97
BHF 58.12
BHGE 31.71
BIIB 321.15
BK 54.27
BLK 518.78
BLL 38.12
BMY 61.4
BRK.B 198.87
BSX 24.94
BWA 51.38
BXP 130.39
CAG 37.68
CAH 61.7
CAT 158.3
CA 33.46
CBG 43.68
CBOE 124.88
CBS 58.19
CB 146.42
CCI 110.53
CCL 67.22
CDNS 42.0
CELG 105.29
CERN 67.55
CFG 42.35
CF 42.86
CHD 50.07
CHK 4.05
CHRW 89.74
CHTR 338.43
CINF 75.37
CI 204.14
CLX 148.79
CL 75.43
CMA 87.36
CMCSA 40.39
CME 146.12
CMG 290.9
CMI 177.51
CMS 47.39
CNC 100.7
CNP 28.39
COF 100.08
COG 28.31
COL 135.8
COO 217.92
COP 55.09
COST 187.23
COTY 19.95
CPB 48.2
CRM 102.88
CSCO 38.67
CSRA 30.01
CSX 55.63
CTAS 157.26
CTL 16.85
CTSH 71.16
CTXS 88.58
CVS 73.06
CVX 125.71
CXO 150.87
C 75.09
DAL 56.29
DE 156.67
DFS 77.24
DGX 98.77
DG 93.56
DHI 51.37
DHR 93.18
DISCA 22.96
DISCK 21.48
DISH 48.41
DIS 108.95
DLR 114.04
DLTR 107.99
DOV 101.45
DPS 97.37
DRE 27.24
DRI 96.78
DTE 109.68
DUK 84.28
DVA 72.27
DVN 41.79
DWDP 71.57
DXC 94.9
D 81.2
EA 106.15
EBAY 38.17
ECL 134.2
ED 84.75
EFX 118.17
EIX 63.63
EL 127.64
EMN 93.43
EMR 70.06
EOG 108.67
EQIX 453.53
EQR 63.97
EQT 57.51
ESRX 74.99
ESS 241.96
ES 63.18
ETFC 50.16
ETN 79.23
ETR 81.71
EVHC 34.56
EW 111.68
EXC 39.54
EXPD 66.25
EXPE 120.64
EXR 87.75
FAST 55.13
FBHS 68.71
FB 177.68
FCX 19.05
FDX 250.83
FE 30.72
FFIV 131.64
FISV 131.96
FIS 94.31
FITB 31.19
FLIR 46.77
FLR 51.8
FLS 42.45
FL 47.45
FMC 95.38
FOXA 34.77
FOX 34.38
FRT 133.08
FTI 31.23
FTV 72.99
F 12.52
GD 203.54
GE 17.58
GGP 23.47
GILD 72.19
GIS 59.43
GLW 32.32
GM 41.24
GOOGL 1053.02
GOOG 1048.34
GPC 95.54
GPN 100.69
GPS 34.15
GRMN 59.64
GS 257.77
GT 32.42
GWW 237.05
HAL 48.92
HAS 91.56
HBAN 14.71
HBI 21.0
HCA 88.0
HCN 63.91
HCP 26.08
HD 190.21
HES 47.97
HIG 56.34
HII 235.46
HLT 80.28
HOG 51.18
HOLX 42.75
HON 153.82
HPE 14.43
HPQ 21.18
HP 65.17
HRB 26.45
HRL 36.53
HRS 142.04
HSIC 70.36
HST 19.97
HSY 113.48
HUM 249.36
IBM 154.5
ICE 70.77
IDXX 157.59
IFF 153.04
ILMN 224.78
INCY 97.36
INFO 45.95
INTC 46.38
INTU 158.22
IPG 19.32
IP 58.7
IQV 98.52
IRM 37.8
IR 89.73
ISRG 367.89
ITW 167.31
IT 123.24
IVZ 36.84
JBHT 115.96
JCI 38.32
JEC 66.5
JNJ 139.66
JNPR 28.73
JPM 107.63
JWN 48.76
KEY 20.32
KHC 78.22
KIM 18.24
KLAC 105.76
KMB 120.81
KMI 18.32
KMX 64.26
KORS 63.18
KO 45.91
KR 27.54
KSS 54.79
KSU 106.28
K 68.03
LB 61.25
LEG 47.93
LEN 63.93
LH 160.0
LKQ 41.04
LLL 198.47
LLY 84.46
LMT 322.0
LNC 77.99
LNT 42.62
LOW 93.02
LRCX 185.15
LUK 26.55
LUV 65.91
LYB 111.05
L 50.24
MAA 100.6
MAC 66.08
MAR 135.89
MAS 44.05
MAT 15.42
MA 152.01
MCD 173.73
MCHP 88.58
MCK 156.91
MCO 147.96
MDLZ 43.22
MDT 82.16
MET 50.81
MGM 32.99
MHK 277.04
MKC 102.01
MLM 222.62
MMC 81.84
MMM 235.78
MNST 63.4
MON 117.05
MOS 25.95
MO 71.51
MPC 66.11
MRK 56.59
MRO 17.11
MSFT 86.125
MSI 90.84
MS 52.76
MTB 172.48
MTD 622.44
MU 41.54
MYL 42.35
M 25.81
NAVI 13.45
NBL 29.4
NCLH 53.76
NDAQ 77.15
NEE 156.43
NEM 37.87
NFLX 196.1
NFX 31.84
NI 25.64
NKE 62.85
NLSN 36.4
NOC 307.35
NOV 36.13
NRG 28.57
NSC 145.96
NTAP 55.5
NTRS 104.84
NUE 64.21
NVDA 195.78
NWL 31.09
NWSA 16.3
NWS 16.65
OKE 53.76
OMC 72.66
ORCL 47.57
ORLY 241.34
OXY 74.01
O 57.02
PAYX 68.34
PBCT 18.83
PCAR 72.57
PCG 44.34
PCLN 1750.09
PDCO 36.55
PEG 51.5
PEP 119.93
PFE 36.38
PFG 71.18
PGR 56.46
PG 91.92
PHM 33.45
PH 200.1
PKG 121.47
PKI 73.71
PLD 64.59
PM 105.82
PNC 145.25
PNR 71.0
PNW 85.3
PPG 116.98
PPL 31.08
PRGO 87.75
PRU 115.17
PSA 210.05
PSX 101.66
PVH 137.59
PWR 39.29
PXD 174.3
PX 154.76
PYPL 74.235
QCOM 64.38
QRVO 67.06
RCL 120.17
REGN 379.48
REG 69.33
RE 222.64
RF 17.39
RHI 55.81
RHT 121.04
RJF 89.61
RL 103.41
RMD 85.2
ROK 197.81
ROP 260.44
ROST 80.86
RRC 17.66
RSG 67.57
RTN 187.49
SBAC 163.08
SBUX 57.95
SCG 39.93
SCHW 51.55
SEE 49.49
SHW 410.59
SIG 56.74
SJM 124.38
SLB 68.07
SLG 101.05
SNA 174.58
SNI 85.85
SNPS 85.9
SO 48.01
SPGI 169.74
SPG 172.34
SRCL 68.29
SRE 107.24
STI 65.07
STT 98.25
STX 42.35
STZ 229.0
SWKS 96.0
SWK 170.52
SYF 38.8
SYK 156.65
SYMC 28.26
SYY 60.69
TAP 82.24
TDG 275.46
TEL 95.71
TGT 65.95
TIF 104.57
TJX 76.86
TMK 91.42
TMO 190.8
TPR 44.37
TRIP 34.61
TROW 104.44
TRV 136.3
TSCO 75.35
TSN 81.12
TSS 79.26
TWX 91.74
TXN 105.11
TXT 56.9
T 39.06
UAA 14.59
UAL 67.9
UA 13.45
UDR 38.57
UHS 114.16
ULTA 224.44
UNH 221.02
UNM 55.44
UNP 134.71
UPS 120.04
URI 172.92
USB 54.05
UTX 127.9
VAR 111.14
VFC 74.42
VIAB 30.51
VLO 92.19
VMC 129.75
VNO 78.31
VRSK 96.48
VRSN 114.69
VRTX 150.0
VTR 60.08
VZ 53.16
V 114.57
WAT 194.12
WBA 73.28
WDC 80.51
WEC 66.43
WFC 61.04
WHR 169.17
WLTW 156.52
WMB 30.67
WMT 99.3
WM 86.15
WRK 63.65
WU 19.06
WYNN 165.11
WYN 116.59
WY 35.3
XEC 122.74
XEL 48.22
XLNX 67.9
XL 35.21
XOM 83.82
XRAY 66.0
XRX 29.38
XYL 68.21
YUM 82.15
ZBH 121.0
ZION 52.17
ZTS 72.54


Total time to return each company's opening price using dictionaries:
--- 0.07394099235534668 seconds ---

### Get opening values for all companies on 2018-01-02 with dataframes, print and time it

In [34]:
def get_opening_values_with_df():
    for company in data['Name'].unique():
        print(company, data[(data['Name'] == company) & (data['date'] == '2018-01-02')].reset_index(drop=True).iat[0,1])

In [36]:
#time to get all opening values with dataframe
print("Gathering opening prices using dataframes \n")
start_time = time.time()
get_opening_values_with_df()
df_time = time.time() - start_time
print("\n\nTotal time to return each company's opening price using dataframes: \n --- %s seconds ---" % (time.time() - start_time))

Gathering opening prices using dataframes

AAL 52.33
AAPL 170.16
AAP 100.9
ABBV 97.14
ABC 92.15
ABT 58.2
ACN 153.5
ADBE 175.85
ADI 89.24
ADM 40.2
ADP 116.03
ADSK 105.34
ADS 254.29
AEE 58.98
AEP 73.18
AES 10.87
AET 180.94
AFL 88.36
AGN 164.05
AIG 60.0
AIV 43.79
AIZ 101.44
AJG 63.55
AKAM 65.13
ALB 128.93
ALGN 222.61
ALK 74.04
ALLE 80.07
ALL 104.07
ALXN 121.63
AMAT 51.68
AMD 10.42
AME 72.89
AMGN 175.35
AMG 206.52
AMP 170.64
AMT 143.16
AMZN 1172.0
ANDV 114.92
ANSS 148.15
ANTM 225.0
AON 134.25
AOS 61.45
APA 42.65
APC 54.13
APD 164.88
APH 88.47
APTV 84.89
ARE 131.0
ARNC 27.31
ATVI 63.54
AVB 178.59
AVGO 259.77
AVY 115.15
AWK 91.0
AXP 99.73
AYI 176.67
AZO 716.54
A 67.42
BAC 29.75
BAX 66.09
BA 295.75
BBT 50.0
BBY 68.26
BDX 215.09
BEN 43.77
BF.B 68.97
BHF 58.12
BHGE 31.71
BIIB 321.15
BK 54.27
BLK 518.78
BLL 38.12
BMY 61.4
BRK.B 198.87
BSX 24.94
BWA 51.38
BXP 130.39
CAG 37.68
CAH 61.7
CAT 158.3
CA 33.46
CBG 43.68
CBOE 124.88
CBS 58.19
CB 146.42
CCI 110.53
CCL 67.22
CDNS 42.0
CELG 105.29
CERN 67.55
CFG 42.35
CF 42.86
CHD 50.07
CHK 4.05
CHRW 89.74
CHTR 338.43
CINF 75.37
CI 204.14
CLX 148.79
CL 75.43
CMA 87.36
CMCSA 40.39
CME 146.12
CMG 290.9
CMI 177.51
CMS 47.39
CNC 100.7
CNP 28.39
COF 100.08
COG 28.31
COL 135.8
COO 217.92
COP 55.09
COST 187.23
COTY 19.95
CPB 48.2
CRM 102.88
CSCO 38.67
CSRA 30.01
CSX 55.63
CTAS 157.26
CTL 16.85
CTSH 71.16
CTXS 88.58
CVS 73.06
CVX 125.71
CXO 150.87
C 75.09
DAL 56.29
DE 156.67
DFS 77.24
DGX 98.77
DG 93.56
DHI 51.37
DHR 93.18
DISCA 22.96
DISCK 21.48
DISH 48.41
DIS 108.95
DLR 114.04
DLTR 107.99
DOV 101.45
DPS 97.37
DRE 27.24
DRI 96.78
DTE 109.68
DUK 84.28
DVA 72.27
DVN 41.79
DWDP 71.57
DXC 94.9
D 81.2
EA 106.15
EBAY 38.17
ECL 134.2
ED 84.75
EFX 118.17
EIX 63.63
EL 127.64
EMN 93.43
EMR 70.06
EOG 108.67
EQIX 453.53
EQR 63.97
EQT 57.51
ESRX 74.99
ESS 241.96
ES 63.18
ETFC 50.16
ETN 79.23
ETR 81.71
EVHC 34.56
EW 111.68
EXC 39.54
EXPD 66.25
EXPE 120.64
EXR 87.75
FAST 55.13
FBHS 68.71
FB 177.68
FCX 19.05
FDX 250.83
FE 30.72
FFIV 131.64
FISV 131.96
FIS 94.31
FITB 31.19
FLIR 46.77
FLR 51.8
FLS 42.45
FL 47.45
FMC 95.38
FOXA 34.77
FOX 34.38
FRT 133.08
FTI 31.23
FTV 72.99
F 12.52
GD 203.54
GE 17.58
GGP 23.47
GILD 72.19
GIS 59.43
GLW 32.32
GM 41.24
GOOGL 1053.02
GOOG 1048.34
GPC 95.54
GPN 100.69
GPS 34.15
GRMN 59.64
GS 257.77
GT 32.42
GWW 237.05
HAL 48.92
HAS 91.56
HBAN 14.71
HBI 21.0
HCA 88.0
HCN 63.91
HCP 26.08
HD 190.21
HES 47.97
HIG 56.34
HII 235.46
HLT 80.28
HOG 51.18
HOLX 42.75
HON 153.82
HPE 14.43
HPQ 21.18
HP 65.17
HRB 26.45
HRL 36.53
HRS 142.04
HSIC 70.36
HST 19.97
HSY 113.48
HUM 249.36
IBM 154.5
ICE 70.77
IDXX 157.59
IFF 153.04
ILMN 224.78
INCY 97.36
INFO 45.95
INTC 46.38
INTU 158.22
IPG 19.32
IP 58.7
IQV 98.52
IRM 37.8
IR 89.73
ISRG 367.89
ITW 167.31
IT 123.24
IVZ 36.84
JBHT 115.96
JCI 38.32
JEC 66.5
JNJ 139.66
JNPR 28.73
JPM 107.63
JWN 48.76
KEY 20.32
KHC 78.22
KIM 18.24
KLAC 105.76
KMB 120.81
KMI 18.32
KMX 64.26
KORS 63.18
KO 45.91
KR 27.54
KSS 54.79
KSU 106.28
K 68.03
LB 61.25
LEG 47.93
LEN 63.93
LH 160.0
LKQ 41.04
LLL 198.47
LLY 84.46
LMT 322.0
LNC 77.99
LNT 42.62
LOW 93.02
LRCX 185.15
LUK 26.55
LUV 65.91
LYB 111.05
L 50.24
MAA 100.6
MAC 66.08
MAR 135.89
MAS 44.05
MAT 15.42
MA 152.01
MCD 173.73
MCHP 88.58
MCK 156.91
MCO 147.96
MDLZ 43.22
MDT 82.16
MET 50.81
MGM 32.99
MHK 277.04
MKC 102.01
MLM 222.62
MMC 81.84
MMM 235.78
MNST 63.4
MON 117.05
MOS 25.95
MO 71.51
MPC 66.11
MRK 56.59
MRO 17.11
MSFT 86.125
MSI 90.84
MS 52.76
MTB 172.48
MTD 622.44
MU 41.54
MYL 42.35
M 25.81
NAVI 13.45
NBL 29.4
NCLH 53.76
NDAQ 77.15
NEE 156.43
NEM 37.87
NFLX 196.1
NFX 31.84
NI 25.64
NKE 62.85
NLSN 36.4
NOC 307.35
NOV 36.13
NRG 28.57
NSC 145.96
NTAP 55.5
NTRS 104.84
NUE 64.21
NVDA 195.78
NWL 31.09
NWSA 16.3
NWS 16.65
OKE 53.76
OMC 72.66
ORCL 47.57
ORLY 241.34
OXY 74.01
O 57.02
PAYX 68.34
PBCT 18.83
PCAR 72.57
PCG 44.34
PCLN 1750.09
PDCO 36.55
PEG 51.5
PEP 119.93
PFE 36.38
PFG 71.18
PGR 56.46
PG 91.92
PHM 33.45
PH 200.1
PKG 121.47
PKI 73.71
PLD 64.59
PM 105.82
PNC 145.25
PNR 71.0
PNW 85.3
PPG 116.98
PPL 31.08
PRGO 87.75
PRU 115.17
PSA 210.05
PSX 101.66
PVH 137.59
PWR 39.29
PXD 174.3
PX 154.76
PYPL 74.235
QCOM 64.38
QRVO 67.06
RCL 120.17
REGN 379.48
REG 69.33
RE 222.64
RF 17.39
RHI 55.81
RHT 121.04
RJF 89.61
RL 103.41
RMD 85.2
ROK 197.81
ROP 260.44
ROST 80.86
RRC 17.66
RSG 67.57
RTN 187.49
SBAC 163.08
SBUX 57.95
SCG 39.93
SCHW 51.55
SEE 49.49
SHW 410.59
SIG 56.74
SJM 124.38
SLB 68.07
SLG 101.05
SNA 174.58
SNI 85.85
SNPS 85.9
SO 48.01
SPGI 169.74
SPG 172.34
SRCL 68.29
SRE 107.24
STI 65.07
STT 98.25
STX 42.35
STZ 229.0
SWKS 96.0
SWK 170.52
SYF 38.8
SYK 156.65
SYMC 28.26
SYY 60.69
TAP 82.24
TDG 275.46
TEL 95.71
TGT 65.95
TIF 104.57
TJX 76.86
TMK 91.42
TMO 190.8
TPR 44.37
TRIP 34.61
TROW 104.44
TRV 136.3
TSCO 75.35
TSN 81.12
TSS 79.26
TWX 91.74
TXN 105.11
TXT 56.9
T 39.06
UAA 14.59
UAL 67.9
UA 13.45
UDR 38.57
UHS 114.16
ULTA 224.44
UNH 221.02
UNM 55.44
UNP 134.71
UPS 120.04
URI 172.92
USB 54.05
UTX 127.9
VAR 111.14
VFC 74.42
VIAB 30.51
VLO 92.19
VMC 129.75
VNO 78.31
VRSK 96.48
VRSN 114.69
VRTX 150.0
VTR 60.08
VZ 53.16
V 114.57
WAT 194.12
WBA 73.28
WDC 80.51
WEC 66.43
WFC 61.04
WHR 169.17
WLTW 156.52
WMB 30.67
WMT 99.3
WM 86.15
WRK 63.65
WU 19.06
WYNN 165.11
WYN 116.59
WY 35.3
XEC 122.74
XEL 48.22
XLNX 67.9
XL 35.21
XOM 83.82
XRAY 66.0
XRX 29.38
XYL 68.21
YUM 82.15
ZBH 121.0
ZION 52.17
ZTS 72.54


Total time to return each company's opening price using dataframes:
 --- 37.77716898918152 seconds ---

#### Speed Results:

In [38]:
# print('Df:Dict Lookup Ratio',df_time/dict_time)

# print speed ratio as how much faster df
try:
    print('Dictionary search is: ',df_time/dict_time, ' times faster')
except:
    print('Cannot divide by zero')

Dictionary search is:  511.1152590595021  times faster

### Final comparison of only performing lookup with dictionaries vs dataframe

In [40]:
#Time to perform lookup with dictionaries
dict_values = []
def main3():
    for company in data['Name'].unique():
        dict_values.append(data_dict[company]['2018-01-02']['open'])
#########################################################
start_time = time.time()
main3()
dict_time_delta = (time.time() - start_time)
# print("--- %s seconds ---" % (time.time() - start_time))
print("Dictionary search took: \n --- %s seconds ---" % (time.time() - start_time))

Dictionary search took:
 --- 0.01847982406616211 seconds ---

In [42]:
#Time to perform lookup with df
df_values = []
def main4():
    for company in data['Name'].unique():
        df_values.append(data[(data['Name'] == company) & (data['date'] == '2018-01-02')].reset_index(drop=True).iat[0,1])
#########################################################
start_time = time.time()
main4()
df_time_delta = (time.time() - start_time)
# print("--- %s seconds ---" % (time.time() - start_time))
print("Dataframe search took: \n --- %s seconds ---" % (time.time() - start_time))

Dataframe search took:
 --- 37.501580238342285 seconds ---

In [49]:
#time comparisons without print statement used
print('Total dataframe methods time for all companies took: \n \n',df_time_delta/dict_time_delta)
print("\n times as long as dictionary method.")

Total dataframe methods time for all companies took:

 2033.1799180486796

 times as long as dictionary method.

## Set and List Differences

In [50]:
#Get dates with data
date_list = data['date'].unique().tolist()

In [51]:
increased_price = []
for company in company_list:
    if data_dict[company]['2018-01-02']['close'] > data_dict[company]['2018-01-02']['open']:
        increased_price.append(company)
    else:
        pass

print('Companies where price increased on 2018-01-02:',len(increased_price))
print('Total number of companies:',len(company_list))

Companies where price increased on 2018-01-02: 273
Total number of companies: 505

In [52]:
#Get companies where price was not higher at end of the day using o(n^2) (this is just an example)
did_not_go_up_linear = []

def went_down_linear():
    for company in company_list:
        if company in increased_price:
            pass
        else:
            did_not_go_up_linear.append(company)

In [53]:
start_time = time.time()
went_down_linear()
print("--- %s seconds ---" % (time.time() - start_time))
linear_list_diff = (time.time() - start_time)

--- 0.0015869140625 seconds ---

In [54]:
company_list = set(company_list)
increased_price = set(increased_price)
def went_down_set():
    did_not_go_up = company_list - increased_price

In [55]:
start_time = time.time()
went_down_set()
print("--- %s seconds ---" % (time.time() - start_time))
set_diff = (time.time() - start_time)

--- 0.0001227855682373047 seconds ---

In [56]:
try:
    print('Nested linear search:Set difference search ratio:',linear_list_diff/set_diff)
except:
    print('Cannot divide by zero')

Nested linear search:Set difference search ratio: 4.907491856677525

In [57]:
company_price_did_not_go_up = []
for company in company_list:
    if company in increased_price:
        pass
    else:
        company_price_did_not_go_up.append(company)
print(len(company_price_did_not_go_up),'companies found via linear search')

print(len(set(company_list) - set(increased_price)),'companies found via set difference')

first = company_price_did_not_go_up
second = set(company_list) - set(increased_price)

for item in first:
    if item not in second:
        print(item)

232 companies found via linear search
232 companies found via set difference

## Conclusion

###### source: https://medium.freecodecamp.org/my-first-foray-into-technology-c5b6e83fe8f1

In [58]:
Image(url= "https://cdn-images-1.medium.com/max/2000/1*HwLR-DKk0lYNEMpkH475kg.png")