In [1]:
import pandas as pd

In [2]:
data = pd.read_csv('stocks.csv')

In [3]:
data

              date   open     high      low  close    volume Name
0       2013-02-08  15.07  15.1200  14.6300  14.75   8407500  AAL
1       2013-02-11  14.89  15.0100  14.2600  14.46   8882000  AAL
2       2013-02-12  14.45  14.5100  14.1000  14.27   8126000  AAL
3       2013-02-13  14.30  14.9400  14.2500  14.66  10259500  AAL
4       2013-02-14  14.94  14.9600  13.1600  13.99  31879900  AAL
5       2013-02-15  13.93  14.6100  13.9300  14.50  15628000  AAL
6       2013-02-19  14.33  14.5600  14.0800  14.26  11354400  AAL
7       2013-02-20  14.17  14.2600  13.1500  13.33  14725200  AAL
8       2013-02-21  13.62  13.9500  12.9000  13.37  11922100  AAL
9       2013-02-22  13.57  13.6000  13.2100  13.57   6071400  AAL
10      2013-02-25  13.60  13.7600  13.0000  13.02   7186400  AAL
11      2013-02-26  13.14  13.4200  12.7000  13.26   9419000  AAL
12      2013-02-27  13.28  13.6200  13.1800  13.41   7390500  AAL
13      2013-02-28  13.49  13.6300  13.3900  13.43   6143600  AAL
14      2013-03-01  13.37  13.9500  13.3200  13.61   7376800  AAL
15      2013-03-04  13.50  14.0700  13.4700  13.90   8174800  AAL
16      2013-03-05  14.01  14.0500  13.7100  14.05   7676100  AAL
17      2013-03-06  14.52  14.6800  14.2500  14.57  13243200  AAL
18      2013-03-07  14.70  14.9300  14.5000  14.82   9125300  AAL
19      2013-03-08  14.99  15.2000  14.8400  14.92  10593700  AAL
20      2013-03-11  14.85  15.1500  14.7100  15.13   6961800  AAL
21      2013-03-12  15.14  15.6000  14.9500  15.50   8999100  AAL
22      2013-03-13  15.54  16.2000  15.4800  15.91  11380000  AAL
23      2013-03-14  15.98  16.3600  15.9300  16.25   8383300  AAL
24      2013-03-15  16.45  16.5400  15.8800  15.98  17667700  AAL
25      2013-03-18  15.80  16.3300  15.7100  16.29   6514100  AAL
26      2013-03-19  16.48  16.8500  16.4100  16.78  11805300  AAL
27      2013-03-20  17.13  17.3300  16.8700  17.23  10819800  AAL
28      2013-03-21  17.21  17.4300  16.8700  17.00  10740800  AAL
29      2013-03-22  17.10  17.2900  16.7700  16.86   8545200  AAL
...            ...    ...      ...      ...    ...       ...  ...
619010  2017-12-26  72.40  72.5500  71.9000  72.34    792134  ZTS
619011  2017-12-27  72.59  72.6900  72.2500  72.45   1159771  ZTS
619012  2017-12-28  72.49  72.6000  72.1400  72.39    710499  ZTS
619013  2017-12-29  72.55  72.7600  72.0400  72.04   1704122  ZTS
619014  2018-01-02  72.54  72.5900  71.4650  71.77   2135564  ZTS
619015  2018-01-03  71.77  72.1800  71.3400  72.10   2328506  ZTS
619016  2018-01-04  72.75  72.9128  72.2600  72.53   2534010  ZTS
619017  2018-01-05  72.83  73.9200  72.5700  73.36   2166065  ZTS
619018  2018-01-08  73.43  74.4200  73.1607  74.24   3631552  ZTS
619019  2018-01-09  74.70  75.4750  74.4650  75.11   2721946  ZTS
619020  2018-01-10  74.58  74.8000  73.2800  73.91   2257464  ZTS
619021  2018-01-11  74.05  74.6800  73.7200  74.59   1629279  ZTS
619022  2018-01-12  74.91  75.6900  74.7700  75.39   1915669  ZTS
619023  2018-01-16  76.06  76.4000  75.2100  75.54   2599094  ZTS
619024  2018-01-17  75.81  77.0300  75.3900  76.77   2769587  ZTS
619025  2018-01-18  76.65  76.6500  75.8500  76.33   2588995  ZTS
619026  2018-01-19  76.69  76.9100  76.2200  76.62   4829602  ZTS
619027  2018-01-22  76.67  77.5800  76.6200  77.48   4195103  ZTS
619028  2018-01-23  77.30  78.3200  76.9700  77.59   2264132  ZTS
619029  2018-01-24  78.16  78.5100  77.6000  78.33   2585326  ZTS
619030  2018-01-25  78.47  79.3800  78.3450  79.25   2327262  ZTS
619031  2018-01-26  79.49  80.1300  79.3800  80.09   2532808  ZTS
619032  2018-01-29  79.81  79.9500  79.1100  79.18   2662383  ZTS
619033  2018-01-30  78.44  78.6900  77.9100  78.35   3808707  ZTS
619034  2018-01-31  78.49  78.7700  76.5400  76.73   4136360  ZTS
619035  2018-02-01  76.84  78.2700  76.6900  77.82   2982259  ZTS
619036  2018-02-02  77.53  78.1200  76.7300  76.78   2595187  ZTS
619037  2018-02-05  76.64  76.9200  73.1800  73.83   2962031  ZTS
619038  2018-02-06  72.74  74.5600  72.1300  73.27   4924323  ZTS
619039  2018-02-07  72.70  75.0000  72.6900  73.86   4534912  ZTS

[619040 rows x 7 columns]

In [6]:
data_dict = {}
for i in range(0,len(data)):
    values = {}
    dates = {}
    names = {}
    date = data.iat[i,0]
    _open = data.iat[i,1]
    _close = data.iat[i,4]
    _high = data.iat[i,2]
    _low = data.iat[i,3]
    name = data.iat[i,6]
    volume = data.iat[i,5]
    values['open'] = _open
    values['close'] = _close
    values['high'] = _high
    values['low'] = _low
    if name not in data_dict:
        date_dict = {}
        values_dict = {}
        date_dict[date] = {'open':_open,'close':_close,'low':_low,'high':_high,'volume':volume}
        data_dict[name] = date_dict
    else:
        date_dict[date] = {'open':_open,'close':_close,'low':_low,'high':_high,'volume':volume}

In [9]:
#Get unique company names
data['Name'].unique()

array(['AAL', 'AAPL', 'AAP', 'ABBV', 'ABC', 'ABT', 'ACN', 'ADBE', 'ADI',
       'ADM', 'ADP', 'ADSK', 'ADS', 'AEE', 'AEP', 'AES', 'AET', 'AFL',
       'AGN', 'AIG', 'AIV', 'AIZ', 'AJG', 'AKAM', 'ALB', 'ALGN', 'ALK',
       'ALLE', 'ALL', 'ALXN', 'AMAT', 'AMD', 'AME', 'AMGN', 'AMG', 'AMP',
       'AMT', 'AMZN', 'ANDV', 'ANSS', 'ANTM', 'AON', 'AOS', 'APA', 'APC',
       'APD', 'APH', 'APTV', 'ARE', 'ARNC', 'ATVI', 'AVB', 'AVGO', 'AVY',
       'AWK', 'AXP', 'AYI', 'AZO', 'A', 'BAC', 'BAX', 'BA', 'BBT', 'BBY',
       'BDX', 'BEN', 'BF.B', 'BHF', 'BHGE', 'BIIB', 'BK', 'BLK', 'BLL',
       'BMY', 'BRK.B', 'BSX', 'BWA', 'BXP', 'CAG', 'CAH', 'CAT', 'CA',
       'CBG', 'CBOE', 'CBS', 'CB', 'CCI', 'CCL', 'CDNS', 'CELG', 'CERN',
       'CFG', 'CF', 'CHD', 'CHK', 'CHRW', 'CHTR', 'CINF', 'CI', 'CLX',
       'CL', 'CMA', 'CMCSA', 'CME', 'CMG', 'CMI', 'CMS', 'CNC', 'CNP',
       'COF', 'COG', 'COL', 'COO', 'COP', 'COST', 'COTY', 'CPB', 'CRM',
       'CSCO', 'CSRA', 'CSX', 'CTAS', 'CTL', 'CTSH', 'CTXS', 'CVS', 'CVX',
       'CXO', 'C', 'DAL', 'DE', 'DFS', 'DGX', 'DG', 'DHI', 'DHR', 'DISCA',
       'DISCK', 'DISH', 'DIS', 'DLR', 'DLTR', 'DOV', 'DPS', 'DRE', 'DRI',
       'DTE', 'DUK', 'DVA', 'DVN', 'DWDP', 'DXC', 'D', 'EA', 'EBAY',
       'ECL', 'ED', 'EFX', 'EIX', 'EL', 'EMN', 'EMR', 'EOG', 'EQIX',
       'EQR', 'EQT', 'ESRX', 'ESS', 'ES', 'ETFC', 'ETN', 'ETR', 'EVHC',
       'EW', 'EXC', 'EXPD', 'EXPE', 'EXR', 'FAST', 'FBHS', 'FB', 'FCX',
       'FDX', 'FE', 'FFIV', 'FISV', 'FIS', 'FITB', 'FLIR', 'FLR', 'FLS',
       'FL', 'FMC', 'FOXA', 'FOX', 'FRT', 'FTI', 'FTV', 'F', 'GD', 'GE',
       'GGP', 'GILD', 'GIS', 'GLW', 'GM', 'GOOGL', 'GOOG', 'GPC', 'GPN',
       'GPS', 'GRMN', 'GS', 'GT', 'GWW', 'HAL', 'HAS', 'HBAN', 'HBI',
       'HCA', 'HCN', 'HCP', 'HD', 'HES', 'HIG', 'HII', 'HLT', 'HOG',
       'HOLX', 'HON', 'HPE', 'HPQ', 'HP', 'HRB', 'HRL', 'HRS', 'HSIC',
       'HST', 'HSY', 'HUM', 'IBM', 'ICE', 'IDXX', 'IFF', 'ILMN', 'INCY',
       'INFO', 'INTC', 'INTU', 'IPG', 'IP', 'IQV', 'IRM', 'IR', 'ISRG',
       'ITW', 'IT', 'IVZ', 'JBHT', 'JCI', 'JEC', 'JNJ', 'JNPR', 'JPM',
       'JWN', 'KEY', 'KHC', 'KIM', 'KLAC', 'KMB', 'KMI', 'KMX', 'KORS',
       'KO', 'KR', 'KSS', 'KSU', 'K', 'LB', 'LEG', 'LEN', 'LH', 'LKQ',
       'LLL', 'LLY', 'LMT', 'LNC', 'LNT', 'LOW', 'LRCX', 'LUK', 'LUV',
       'LYB', 'L', 'MAA', 'MAC', 'MAR', 'MAS', 'MAT', 'MA', 'MCD', 'MCHP',
       'MCK', 'MCO', 'MDLZ', 'MDT', 'MET', 'MGM', 'MHK', 'MKC', 'MLM',
       'MMC', 'MMM', 'MNST', 'MON', 'MOS', 'MO', 'MPC', 'MRK', 'MRO',
       'MSFT', 'MSI', 'MS', 'MTB', 'MTD', 'MU', 'MYL', 'M', 'NAVI', 'NBL',
       'NCLH', 'NDAQ', 'NEE', 'NEM', 'NFLX', 'NFX', 'NI', 'NKE', 'NLSN',
       'NOC', 'NOV', 'NRG', 'NSC', 'NTAP', 'NTRS', 'NUE', 'NVDA', 'NWL',
       'NWSA', 'NWS', 'OKE', 'OMC', 'ORCL', 'ORLY', 'OXY', 'O', 'PAYX',
       'PBCT', 'PCAR', 'PCG', 'PCLN', 'PDCO', 'PEG', 'PEP', 'PFE', 'PFG',
       'PGR', 'PG', 'PHM', 'PH', 'PKG', 'PKI', 'PLD', 'PM', 'PNC', 'PNR',
       'PNW', 'PPG', 'PPL', 'PRGO', 'PRU', 'PSA', 'PSX', 'PVH', 'PWR',
       'PXD', 'PX', 'PYPL', 'QCOM', 'QRVO', 'RCL', 'REGN', 'REG', 'RE',
       'RF', 'RHI', 'RHT', 'RJF', 'RL', 'RMD', 'ROK', 'ROP', 'ROST',
       'RRC', 'RSG', 'RTN', 'SBAC', 'SBUX', 'SCG', 'SCHW', 'SEE', 'SHW',
       'SIG', 'SJM', 'SLB', 'SLG', 'SNA', 'SNI', 'SNPS', 'SO', 'SPGI',
       'SPG', 'SRCL', 'SRE', 'STI', 'STT', 'STX', 'STZ', 'SWKS', 'SWK',
       'SYF', 'SYK', 'SYMC', 'SYY', 'TAP', 'TDG', 'TEL', 'TGT', 'TIF',
       'TJX', 'TMK', 'TMO', 'TPR', 'TRIP', 'TROW', 'TRV', 'TSCO', 'TSN',
       'TSS', 'TWX', 'TXN', 'TXT', 'T', 'UAA', 'UAL', 'UA', 'UDR', 'UHS',
       'ULTA', 'UNH', 'UNM', 'UNP', 'UPS', 'URI', 'USB', 'UTX', 'VAR',
       'VFC', 'VIAB', 'VLO', 'VMC', 'VNO', 'VRSK', 'VRSN', 'VRTX', 'VTR',
       'VZ', 'V', 'WAT', 'WBA', 'WDC', 'WEC', 'WFC', 'WHR', 'WLTW', 'WMB',
       'WMT', 'WM', 'WRK', 'WU', 'WYNN', 'WYN', 'WY', 'XEC', 'XEL',
       'XLNX', 'XL', 'XOM', 'XRAY', 'XRX', 'XYL', 'YUM', 'ZBH', 'ZION',
       'ZTS'], dtype=object)

In [7]:
# read in directory of txt files
import os
# for filename in os.listdir(os.getcwd()):
   # do your stuff

path = '/ETFs'

for filename in os.listdir(path):
    # do your stuff
    print(filename)

# for filename in glob.glob(os.path.join(path, '*.txt')):
    # do your stuff

FileNotFoundError: [Errno 2] No such file or directory: '/ETFs'

In [ ]:
# loop through em 
# Echo the contents of a file
  f = open('foo.txt', 'rU')
  for line in f:   ## iterates over the lines of the file
    print line,    ## trailing , so print does not add an end-of-line char
                   ## since 'line' already includes the end-of line.
  f.close()

In [10]:
data[(data['Name'] == 'AMZN') & (data['date'] == '2018-01-02')].reset_index(drop=True).iat[0,1]

1172.0

In [11]:
data_dict['AMZN']['2018-01-02']['open']

1172.0

In [12]:
#Time to perform lookup with dictionaries
def main1():
    return data_dict['AMZN']['2018-01-02']['open']


import time
start_time = time.time()
main1()
print("--- %s seconds ---" % (time.time() - start_time))

--- 5.0067901611328125e-05 seconds ---

In [13]:
#Time to perform lookup with dataframe query as learned in class
def main2():
    return data[(data['Name'] == 'AMZN') & (data['date'] == '2018-01-02')].reset_index(drop=True).iat[0,1]

import time
start_time = time.time()
main2()
print("--- %s seconds ---" % (time.time() - start_time))

--- 0.0721888542175293 seconds ---

In [14]:
#Get opening values for all companies on given date
def get_opening_values_with_dicts():
    for company in data['Name'].unique():
        print(company, data_dict[company]['2018-01-02']['open'])

In [15]:
#time to get all opening values with nested dictionaries
start_time = time.time()
get_opening_values_with_dicts()
dict_time = time.time() - start_time
print("--- %s seconds ---" % (time.time() - start_time))

AAL 52.33
AAPL 170.16
AAP 100.9
ABBV 97.14
ABC 92.15
ABT 58.2
ACN 153.5
ADBE 175.85
ADI 89.24
ADM 40.2
ADP 116.03
ADSK 105.34
ADS 254.29
AEE 58.98
AEP 73.18
AES 10.87
AET 180.94
AFL 88.36
AGN 164.05
AIG 60.0
AIV 43.79
AIZ 101.44
AJG 63.55
AKAM 65.13
ALB 128.93
ALGN 222.61
ALK 74.04
ALLE 80.07
ALL 104.07
ALXN 121.63
AMAT 51.68
AMD 10.42
AME 72.89
AMGN 175.35
AMG 206.52
AMP 170.64
AMT 143.16
AMZN 1172.0
ANDV 114.92
ANSS 148.15
ANTM 225.0
AON 134.25
AOS 61.45
APA 42.65
APC 54.13
APD 164.88
APH 88.47
APTV 84.89
ARE 131.0
ARNC 27.31
ATVI 63.54
AVB 178.59
AVGO 259.77
AVY 115.15
AWK 91.0
AXP 99.73
AYI 176.67
AZO 716.54
A 67.42
BAC 29.75
BAX 66.09
BA 295.75
BBT 50.0
BBY 68.26
BDX 215.09
BEN 43.77
BF.B 68.97
BHF 58.12
BHGE 31.71
BIIB 321.15
BK 54.27
BLK 518.78
BLL 38.12
BMY 61.4
BRK.B 198.87
BSX 24.94
BWA 51.38
BXP 130.39
CAG 37.68
CAH 61.7
CAT 158.3
CA 33.46
CBG 43.68
CBOE 124.88
CBS 58.19
CB 146.42
CCI 110.53
CCL 67.22
CDNS 42.0
CELG 105.29
CERN 67.55
CFG 42.35
CF 42.86
CHD 50.07
CHK 4.05
CHRW 89.74
CHTR 338.43
CINF 75.37
CI 204.14
CLX 148.79
CL 75.43
CMA 87.36
CMCSA 40.39
CME 146.12
CMG 290.9
CMI 177.51
CMS 47.39
CNC 100.7
CNP 28.39
COF 100.08
COG 28.31
COL 135.8
COO 217.92
COP 55.09
COST 187.23
COTY 19.95
CPB 48.2
CRM 102.88
CSCO 38.67
CSRA 30.01
CSX 55.63
CTAS 157.26
CTL 16.85
CTSH 71.16
CTXS 88.58
CVS 73.06
CVX 125.71
CXO 150.87
C 75.09
DAL 56.29
DE 156.67
DFS 77.24
DGX 98.77
DG 93.56
DHI 51.37
DHR 93.18
DISCA 22.96
DISCK 21.48
DISH 48.41
DIS 108.95
DLR 114.04
DLTR 107.99
DOV 101.45
DPS 97.37
DRE 27.24
DRI 96.78
DTE 109.68
DUK 84.28
DVA 72.27
DVN 41.79
DWDP 71.57
DXC 94.9
D 81.2
EA 106.15
EBAY 38.17
ECL 134.2
ED 84.75
EFX 118.17
EIX 63.63
EL 127.64
EMN 93.43
EMR 70.06
EOG 108.67
EQIX 453.53
EQR 63.97
EQT 57.51
ESRX 74.99
ESS 241.96
ES 63.18
ETFC 50.16
ETN 79.23
ETR 81.71
EVHC 34.56
EW 111.68
EXC 39.54
EXPD 66.25
EXPE 120.64
EXR 87.75
FAST 55.13
FBHS 68.71
FB 177.68
FCX 19.05
FDX 250.83
FE 30.72
FFIV 131.64
FISV 131.96
FIS 94.31
FITB 31.19
FLIR 46.77
FLR 51.8
FLS 42.45
FL 47.45
FMC 95.38
FOXA 34.77
FOX 34.38
FRT 133.08
FTI 31.23
FTV 72.99
F 12.52
GD 203.54
GE 17.58
GGP 23.47
GILD 72.19
GIS 59.43
GLW 32.32
GM 41.24
GOOGL 1053.02
GOOG 1048.34
GPC 95.54
GPN 100.69
GPS 34.15
GRMN 59.64
GS 257.77
GT 32.42
GWW 237.05
HAL 48.92
HAS 91.56
HBAN 14.71
HBI 21.0
HCA 88.0
HCN 63.91
HCP 26.08
HD 190.21
HES 47.97
HIG 56.34
HII 235.46
HLT 80.28
HOG 51.18
HOLX 42.75
HON 153.82
HPE 14.43
HPQ 21.18
HP 65.17
HRB 26.45
HRL 36.53
HRS 142.04
HSIC 70.36
HST 19.97
HSY 113.48
HUM 249.36
IBM 154.5
ICE 70.77
IDXX 157.59
IFF 153.04
ILMN 224.78
INCY 97.36
INFO 45.95
INTC 46.38
INTU 158.22
IPG 19.32
IP 58.7
IQV 98.52
IRM 37.8
IR 89.73
ISRG 367.89
ITW 167.31
IT 123.24
IVZ 36.84
JBHT 115.96
JCI 38.32
JEC 66.5
JNJ 139.66
JNPR 28.73
JPM 107.63
JWN 48.76
KEY 20.32
KHC 78.22
KIM 18.24
KLAC 105.76
KMB 120.81
KMI 18.32
KMX 64.26
KORS 63.18
KO 45.91
KR 27.54
KSS 54.79
KSU 106.28
K 68.03
LB 61.25
LEG 47.93
LEN 63.93
LH 160.0
LKQ 41.04
LLL 198.47
LLY 84.46
LMT 322.0
LNC 77.99
LNT 42.62
LOW 93.02
LRCX 185.15
LUK 26.55
LUV 65.91
LYB 111.05
L 50.24
MAA 100.6
MAC 66.08
MAR 135.89
MAS 44.05
MAT 15.42
MA 152.01
MCD 173.73
MCHP 88.58
MCK 156.91
MCO 147.96
MDLZ 43.22
MDT 82.16
MET 50.81
MGM 32.99
MHK 277.04
MKC 102.01
MLM 222.62
MMC 81.84
MMM 235.78
MNST 63.4
MON 117.05
MOS 25.95
MO 71.51
MPC 66.11
MRK 56.59
MRO 17.11
MSFT 86.125
MSI 90.84
MS 52.76
MTB 172.48
MTD 622.44
MU 41.54
MYL 42.35
M 25.81
NAVI 13.45
NBL 29.4
NCLH 53.76
NDAQ 77.15
NEE 156.43
NEM 37.87
NFLX 196.1
NFX 31.84
NI 25.64
NKE 62.85
NLSN 36.4
NOC 307.35
NOV 36.13
NRG 28.57
NSC 145.96
NTAP 55.5
NTRS 104.84
NUE 64.21
NVDA 195.78
NWL 31.09
NWSA 16.3
NWS 16.65
OKE 53.76
OMC 72.66
ORCL 47.57
ORLY 241.34
OXY 74.01
O 57.02
PAYX 68.34
PBCT 18.83
PCAR 72.57
PCG 44.34
PCLN 1750.09
PDCO 36.55
PEG 51.5
PEP 119.93
PFE 36.38
PFG 71.18
PGR 56.46
PG 91.92
PHM 33.45
PH 200.1
PKG 121.47
PKI 73.71
PLD 64.59
PM 105.82
PNC 145.25
PNR 71.0
PNW 85.3
PPG 116.98
PPL 31.08
PRGO 87.75
PRU 115.17
PSA 210.05
PSX 101.66
PVH 137.59
PWR 39.29
PXD 174.3
PX 154.76
PYPL 74.235
QCOM 64.38
QRVO 67.06
RCL 120.17
REGN 379.48
REG 69.33
RE 222.64
RF 17.39
RHI 55.81
RHT 121.04
RJF 89.61
RL 103.41
RMD 85.2
ROK 197.81
ROP 260.44
ROST 80.86
RRC 17.66
RSG 67.57
RTN 187.49
SBAC 163.08
SBUX 57.95
SCG 39.93
SCHW 51.55
SEE 49.49
SHW 410.59
SIG 56.74
SJM 124.38
SLB 68.07
SLG 101.05
SNA 174.58
SNI 85.85
SNPS 85.9
SO 48.01
SPGI 169.74
SPG 172.34
SRCL 68.29
SRE 107.24
STI 65.07
STT 98.25
STX 42.35
STZ 229.0
SWKS 96.0
SWK 170.52
SYF 38.8
SYK 156.65
SYMC 28.26
SYY 60.69
TAP 82.24
TDG 275.46
TEL 95.71
TGT 65.95
TIF 104.57
TJX 76.86
TMK 91.42
TMO 190.8
TPR 44.37
TRIP 34.61
TROW 104.44
TRV 136.3
TSCO 75.35
TSN 81.12
TSS 79.26
TWX 91.74
TXN 105.11
TXT 56.9
T 39.06
UAA 14.59
UAL 67.9
UA 13.45
UDR 38.57
UHS 114.16
ULTA 224.44
UNH 221.02
UNM 55.44
UNP 134.71
UPS 120.04
URI 172.92
USB 54.05
UTX 127.9
VAR 111.14
VFC 74.42
VIAB 30.51
VLO 92.19
VMC 129.75
VNO 78.31
VRSK 96.48
VRSN 114.69
VRTX 150.0
VTR 60.08
VZ 53.16
V 114.57
WAT 194.12
WBA 73.28
WDC 80.51
WEC 66.43
WFC 61.04
WHR 169.17
WLTW 156.52
WMB 30.67
WMT 99.3
WM 86.15
WRK 63.65
WU 19.06
WYNN 165.11
WYN 116.59
WY 35.3
XEC 122.74
XEL 48.22
XLNX 67.9
XL 35.21
XOM 83.82
XRAY 66.0
XRX 29.38
XYL 68.21
YUM 82.15
ZBH 121.0
ZION 52.17
ZTS 72.54
--- 0.08144307136535645 seconds ---

In [18]:
def get_opening_values_with_df():
    for company in data['Name'].unique():
        print(company, data[(data['Name'] == company) & (data['date'] == '2018-01-02')].reset_index(drop=True).iat[0,1])

In [19]:
#time to get all opening values with dataframe
start_time = time.time()
get_opening_values_with_df()
df_time = time.time() - start_time
print("--- %s seconds ---" % (time.time() - start_time))

AAL 52.33
AAPL 170.16
AAP 100.9
ABBV 97.14
ABC 92.15
ABT 58.2
ACN 153.5
ADBE 175.85
ADI 89.24
ADM 40.2
ADP 116.03
ADSK 105.34
ADS 254.29
AEE 58.98
AEP 73.18
AES 10.87
AET 180.94
AFL 88.36
AGN 164.05
AIG 60.0
AIV 43.79
AIZ 101.44
AJG 63.55
AKAM 65.13
ALB 128.93
ALGN 222.61
ALK 74.04
ALLE 80.07
ALL 104.07
ALXN 121.63
AMAT 51.68
AMD 10.42
AME 72.89
AMGN 175.35
AMG 206.52
AMP 170.64
AMT 143.16
AMZN 1172.0
ANDV 114.92
ANSS 148.15
ANTM 225.0
AON 134.25
AOS 61.45
APA 42.65
APC 54.13
APD 164.88
APH 88.47
APTV 84.89
ARE 131.0
ARNC 27.31
ATVI 63.54
AVB 178.59
AVGO 259.77
AVY 115.15
AWK 91.0
AXP 99.73
AYI 176.67
AZO 716.54
A 67.42
BAC 29.75
BAX 66.09
BA 295.75
BBT 50.0
BBY 68.26
BDX 215.09
BEN 43.77
BF.B 68.97
BHF 58.12
BHGE 31.71
BIIB 321.15
BK 54.27
BLK 518.78
BLL 38.12
BMY 61.4
BRK.B 198.87
BSX 24.94
BWA 51.38
BXP 130.39
CAG 37.68
CAH 61.7
CAT 158.3
CA 33.46
CBG 43.68
CBOE 124.88
CBS 58.19
CB 146.42
CCI 110.53
CCL 67.22
CDNS 42.0
CELG 105.29
CERN 67.55
CFG 42.35
CF 42.86
CHD 50.07
CHK 4.05
CHRW 89.74
CHTR 338.43
CINF 75.37
CI 204.14
CLX 148.79
CL 75.43
CMA 87.36
CMCSA 40.39
CME 146.12
CMG 290.9
CMI 177.51
CMS 47.39
CNC 100.7
CNP 28.39
COF 100.08
COG 28.31
COL 135.8
COO 217.92
COP 55.09
COST 187.23
COTY 19.95
CPB 48.2
CRM 102.88
CSCO 38.67
CSRA 30.01
CSX 55.63
CTAS 157.26
CTL 16.85
CTSH 71.16
CTXS 88.58
CVS 73.06
CVX 125.71
CXO 150.87
C 75.09
DAL 56.29
DE 156.67
DFS 77.24
DGX 98.77
DG 93.56
DHI 51.37
DHR 93.18
DISCA 22.96
DISCK 21.48
DISH 48.41
DIS 108.95
DLR 114.04
DLTR 107.99
DOV 101.45
DPS 97.37
DRE 27.24
DRI 96.78
DTE 109.68
DUK 84.28
DVA 72.27
DVN 41.79
DWDP 71.57
DXC 94.9
D 81.2
EA 106.15
EBAY 38.17
ECL 134.2
ED 84.75
EFX 118.17
EIX 63.63
EL 127.64
EMN 93.43
EMR 70.06
EOG 108.67
EQIX 453.53
EQR 63.97
EQT 57.51
ESRX 74.99
ESS 241.96
ES 63.18
ETFC 50.16
ETN 79.23
ETR 81.71
EVHC 34.56
EW 111.68
EXC 39.54
EXPD 66.25
EXPE 120.64
EXR 87.75
FAST 55.13
FBHS 68.71
FB 177.68
FCX 19.05
FDX 250.83
FE 30.72
FFIV 131.64
FISV 131.96
FIS 94.31
FITB 31.19
FLIR 46.77
FLR 51.8
FLS 42.45
FL 47.45
FMC 95.38
FOXA 34.77
FOX 34.38
FRT 133.08
FTI 31.23
FTV 72.99
F 12.52
GD 203.54
GE 17.58
GGP 23.47
GILD 72.19
GIS 59.43
GLW 32.32
GM 41.24
GOOGL 1053.02
GOOG 1048.34
GPC 95.54
GPN 100.69
GPS 34.15
GRMN 59.64
GS 257.77
GT 32.42
GWW 237.05
HAL 48.92
HAS 91.56
HBAN 14.71
HBI 21.0
HCA 88.0
HCN 63.91
HCP 26.08
HD 190.21
HES 47.97
HIG 56.34
HII 235.46
HLT 80.28
HOG 51.18
HOLX 42.75
HON 153.82
HPE 14.43
HPQ 21.18
HP 65.17
HRB 26.45
HRL 36.53
HRS 142.04
HSIC 70.36
HST 19.97
HSY 113.48
HUM 249.36
IBM 154.5
ICE 70.77
IDXX 157.59
IFF 153.04
ILMN 224.78
INCY 97.36
INFO 45.95
INTC 46.38
INTU 158.22
IPG 19.32
IP 58.7
IQV 98.52
IRM 37.8
IR 89.73
ISRG 367.89
ITW 167.31
IT 123.24
IVZ 36.84
JBHT 115.96
JCI 38.32
JEC 66.5
JNJ 139.66
JNPR 28.73
JPM 107.63
JWN 48.76
KEY 20.32
KHC 78.22
KIM 18.24
KLAC 105.76
KMB 120.81
KMI 18.32
KMX 64.26
KORS 63.18
KO 45.91
KR 27.54
KSS 54.79
KSU 106.28
K 68.03
LB 61.25
LEG 47.93
LEN 63.93
LH 160.0
LKQ 41.04
LLL 198.47
LLY 84.46
LMT 322.0
LNC 77.99
LNT 42.62
LOW 93.02
LRCX 185.15
LUK 26.55
LUV 65.91
LYB 111.05
L 50.24
MAA 100.6
MAC 66.08
MAR 135.89
MAS 44.05
MAT 15.42
MA 152.01
MCD 173.73
MCHP 88.58
MCK 156.91
MCO 147.96
MDLZ 43.22
MDT 82.16
MET 50.81
MGM 32.99
MHK 277.04
MKC 102.01
MLM 222.62
MMC 81.84
MMM 235.78
MNST 63.4
MON 117.05
MOS 25.95
MO 71.51
MPC 66.11
MRK 56.59
MRO 17.11
MSFT 86.125
MSI 90.84
MS 52.76
MTB 172.48
MTD 622.44
MU 41.54
MYL 42.35
M 25.81
NAVI 13.45
NBL 29.4
NCLH 53.76
NDAQ 77.15
NEE 156.43
NEM 37.87
NFLX 196.1
NFX 31.84
NI 25.64
NKE 62.85
NLSN 36.4
NOC 307.35
NOV 36.13
NRG 28.57
NSC 145.96
NTAP 55.5
NTRS 104.84
NUE 64.21
NVDA 195.78
NWL 31.09
NWSA 16.3
NWS 16.65
OKE 53.76
OMC 72.66
ORCL 47.57
ORLY 241.34
OXY 74.01
O 57.02
PAYX 68.34
PBCT 18.83
PCAR 72.57
PCG 44.34
PCLN 1750.09
PDCO 36.55
PEG 51.5
PEP 119.93
PFE 36.38
PFG 71.18
PGR 56.46
PG 91.92
PHM 33.45
PH 200.1
PKG 121.47
PKI 73.71
PLD 64.59
PM 105.82
PNC 145.25
PNR 71.0
PNW 85.3
PPG 116.98
PPL 31.08
PRGO 87.75
PRU 115.17
PSA 210.05
PSX 101.66
PVH 137.59
PWR 39.29
PXD 174.3
PX 154.76
PYPL 74.235
QCOM 64.38
QRVO 67.06
RCL 120.17
REGN 379.48
REG 69.33
RE 222.64
RF 17.39
RHI 55.81
RHT 121.04
RJF 89.61
RL 103.41
RMD 85.2
ROK 197.81
ROP 260.44
ROST 80.86
RRC 17.66
RSG 67.57
RTN 187.49
SBAC 163.08
SBUX 57.95
SCG 39.93
SCHW 51.55
SEE 49.49
SHW 410.59
SIG 56.74
SJM 124.38
SLB 68.07
SLG 101.05
SNA 174.58
SNI 85.85
SNPS 85.9
SO 48.01
SPGI 169.74
SPG 172.34
SRCL 68.29
SRE 107.24
STI 65.07
STT 98.25
STX 42.35
STZ 229.0
SWKS 96.0
SWK 170.52
SYF 38.8
SYK 156.65
SYMC 28.26
SYY 60.69
TAP 82.24
TDG 275.46
TEL 95.71
TGT 65.95
TIF 104.57
TJX 76.86
TMK 91.42
TMO 190.8
TPR 44.37
TRIP 34.61
TROW 104.44
TRV 136.3
TSCO 75.35
TSN 81.12
TSS 79.26
TWX 91.74
TXN 105.11
TXT 56.9
T 39.06
UAA 14.59
UAL 67.9
UA 13.45
UDR 38.57
UHS 114.16
ULTA 224.44
UNH 221.02
UNM 55.44
UNP 134.71
UPS 120.04
URI 172.92
USB 54.05
UTX 127.9
VAR 111.14
VFC 74.42
VIAB 30.51
VLO 92.19
VMC 129.75
VNO 78.31
VRSK 96.48
VRSN 114.69
VRTX 150.0
VTR 60.08
VZ 53.16
V 114.57
WAT 194.12
WBA 73.28
WDC 80.51
WEC 66.43
WFC 61.04
WHR 169.17
WLTW 156.52
WMB 30.67
WMT 99.3
WM 86.15
WRK 63.65
WU 19.06
WYNN 165.11
WYN 116.59
WY 35.3
XEC 122.74
XEL 48.22
XLNX 67.9
XL 35.21
XOM 83.82
XRAY 66.0
XRX 29.38
XYL 68.21
YUM 82.15
ZBH 121.0
ZION 52.17
ZTS 72.54
--- 34.504149198532104 seconds ---

In [20]:
print('Df:Dict Lookup Ratio',df_time/dict_time)

Df:Dict Lookup Ratio 423.8318065472181